### ISSUE TITLE
Spawn Amount Multiplier Bug

### ISSUE THREAD

**Issue by P-R-O-L-I-F-I-C** [drizzlx/sacrifice-remix#3]
Currently if i change the spawn amount multiplier to anything at all other than 1, it literally no interactables to spawn, not even the teleporter. leaving it at 1 causes things to spawn but they don't read from my custom options. I disabled all chests and they still spawn.

**Comment by tprussak** [comment]
I am experiencing the same issue.

**Comment by ImJustJoshin** [comment]
Same here.

**Comment by drizzlx** [comment]
This issue was resolved in v1.1.3 -- functionality was removed due to conflicts with artifacts update.
